language: java

jdk:
  - oraclejdk8

install: true

script: ./gradlew clean build --stacktrace

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "kFLpY3MH7ERgT6kM3ALP9bHyp+UKok/+tqdkQDGcUNTcIsRWh/ImOgLXPkSrJRePjpL9+2e8cmvxh0WLHmmxiMcMrVc5FDOcWQKnXsLyeB2KG/qWlNE++M82hGuDgjW7dc8NLgOYUMxeuAUeaCxMVxdUHbwp2ZiTKdQLFunnoBev1G/DGiET/7UAH51jeDALdUunJmCgg9rfolo6urJp4elXg51mNci6Dm9hEsP8X601uFeIA9YDcHntgnFYJgU2FyqUCCRK3PV+h0XW+0LFV0hLltl9aFQapEw7tSxuLkHGuU7r7lCQArRpgS91O8R3mezVsdCelag4T5SnlNQ4j2f1W9IUi3FHI/OcEow5s7cBF8apHxct5LqnMOPRMsDhk2pp20s9qS+AxEQjy/GohS203JiG/hXLP1qQJmAv2eXpvKQmh0Cmrk0oZW+DhlVmIb5m5CcsOvrqrTcxFpW2AJxBkfMUT87E3taUBuy8DtKpHUYrSUGWBX2WNIPBC9AQ4hEC+ywMiArb6DW4wdyq5/CMheCIO1MQvfh/M4yTBobm0EQAa6ootY+jyV3p3X0WE5K53kefpb5xhrs25K5YA6UhVNs0MwXRykFgMnVrnE6LX0RH+XPCacLoowr1dkndi1c6Xt4NGsdtohJrUwUkkNB8CmJ1UEvtLDAaqEHz0pM="
    - secure: "a9bmM23yb4kkCcqVBeVoOXhzjReqBooG2iVFVL6ut6144i3BxU2PXEgc6z1uHSwAnitR9ul/0ZEtE+viCOwPgyXdTUxi/QxgQVmta2nfPdekn95kbQh2+bDjS1lm8VEA1vUF93V7eDavetIX5LRkuBX43WDSwh39cPpFDpELGJshZpMIEDvcQYJ2LmjWLSbd5m0RK1jhfYev+HH8OwxAXe0JdoN+coxXUtsH5+aavnXyp7t5G168JvGlv2lRgTo65QWtw196R4kgXRcCwp2Eu55XuuQId3LzF6WFnAsq+YlG3JQzl8qoe3NFU+wAy3IVR4hDTF8n4iH7ypH72JcV7JEE+1a/gRboCsslvUh5qj8uTYoRmtopBwSR3huQ7Ddnyv8jQoN6GW+FaJpCvyNhiUU9nnQTArNiqfEt3reYUzW8MIPYJ+9YAyJLzgy9WX/g7JzGCFK36nZXMg9vNrllj1Hs77WbK/GLfnnUMWcyCl/V/FuN9wwaHZ8nw3IkrwjFOFAi1NzMMDAtqPQdR6c/6XxO8s9fYiznn6puV/tkGV7zzUDtGbPXCfSssVBLZVQRyMmgLXu3wTt925pXNKX0S2SaZ//pSuIP9Ca4jrUOLMIPRHRmP7eOZyKogiVARDOwh7IUl3uhCQwC8NPdKeG5azUABHKDIvCHD3E2TGD2czw="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
